// Candidaturas que la red ha presentado o está preparando, con su resultado.
// Se muestran en la pestaña "Candidaturas" del radar (/radar/).
//
// Este fichero es PÚBLICO (va al repositorio). Solo datos del proyecto: nada
// de nombres de participantes, PRN, teléfonos ni correos. Las solicitudes
// completas viven en proyectos/, que es un repositorio privado aparte.
//
// Campos:
//   id               identificador único (kebab-case)
//   nombre           título del proyecto
//   organizacion     una de ORGANIZACIONES
//   programa         una de PROGRAMAS
//   accion           código de la acción (KA152, KA155, ESC30, EYF...)
//   agencia          agencia que evalúa (ES02 INJUVE, FR02...)
//   ronda            texto corto ("2026 R2")
//   fechaPresentacion  AAAA-MM-DD o null
//   estado           una de ESTADOS
//   notaEstimada     puntuación de nuestro evaluador simulado (0-100) o null
//   nota             resultado real: { total, criterios: [{ nombre, puntos, max }] } o null
//   importePedido    euros o null
//   importeConcedido euros o null
//   leccion          qué aprendimos (una o dos frases)
//   carpeta          ruta dentro de proyectos/ (para la skill), o null
//   porConfirmar     true si algún dato está pendiente de confirmar

export const ORGANIZACIONES = [
  'Estrellas del Sur',
  'Federación Estrellas de Europa',
  'Étoiles de France',
  'Horizonte Rioja',
  'Estrella del Rif',
];

export const PROGRAMAS = ['Erasmus+', 'Cuerpo Europeo de Solidaridad', 'Consejo de Europa'];

export const ESTADOS = ['preparacion', 'presentada', 'aprobada', 'reserva', 'rechazada'];

// Criterios oficiales por acción (Guide for Experts 2026), para pintar las barras.
export const CRITERIOS = {
  KA152: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA153: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA154: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA155: [['Relevancia', 40], ['Diseño', 40], ['Gestión', 20]],
  ESC30: [['Relevancia', 40], ['Diseño', 40], ['Gestión', 20]],
};

export const ULTIMA_ACTUALIZACION = '2026-10-01';

export const CANDIDATURAS = [
  // ── Ronda de octubre de 2026 ──────────────────────────────────
  {
    id: 'real-ka152',
    nombre: 'Real or Rendered? Youth, AI and Disinformation',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 87,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Intercambio en Madrid con Ucrania y Siria. Con la misma solicitante que un KA152 aprobado, el verificador de originalidad cazó calcos: pasarlo siempre.',
    carpeta: 'erasmus/KA152_REAL_Federacion',
  },
  {
    id: 'cadres-communs-ka152',
    nombre: 'Cadres Communs. Youth Storytelling for Wellbeing and Belonging',
    organizacion: 'Étoiles de France',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'FR02',
    ronda: '2026 Session 2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 86,
    nota: null,
    importePedido: 44150,
    importeConcedido: null,
    leccion: 'Adaptación en francés de un KA152 aprobado a París y seis socias nuevas. Reescribir desde el contexto local, nunca traducir.',
    carpeta: 'erasmus/KA152_Cadres_Communs_Etoiles',
  },
  {
    id: 'ember-ka153',
    nombre: 'EMBER',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Consorcio de ocho socias. Varias versiones de borrador hicieron perder horas: el PDF del portal manda siempre sobre los borradores.',
    carpeta: 'erasmus/KA153_EMBER_EstrellasDelSur',
  },
  {
    id: 'rutas-de-barrio-ka155',
    nombre: 'Rutas de Barrio',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: 19096,
    importeConcedido: null,
    leccion: 'DiscoverEU con jóvenes de Usera y Villaverde. La primera versión se quedó corta (respuestas de 1.300 a 2.000 caracteres); se amplió a 4.000-4.900.',
    carpeta: 'erasmus/KA155_Rutas_de_Barrio_Federacion',
  },
  {
    id: 'billets-d-europe-ka155',
    nombre: "Billets d'Europe",
    organizacion: 'Étoiles de France',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'FR02',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: 22814,
    importeConcedido: null,
    leccion: 'DiscoverEU en francés hacia España y Portugal. También se amplió: el KA155 aprobado de referencia tiene 4.000-5.000 caracteres por respuesta.',
    carpeta: 'erasmus/KA155_Billets_d_Europe_Etoiles',
    porConfirmar: true,
  },
  {
    id: 'orgullo-de-pueblo-ka155',
    nombre: 'Orgullo de Pueblo',
    organizacion: 'Horizonte Rioja',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 88,
    nota: null,
    importePedido: 19234,
    importeConcedido: null,
    leccion: 'Jóvenes LGTBIQ+ rurales con viajes al Coming Out Day y al IDAHOBIT. Un verificador específico de protección evitó riesgos de exposición.',
    carpeta: 'erasmus/KA155_Orgullo_de_Pueblo_Horizonte',
  },
  {
    id: 'conecta-sur-esc30',
    nombre: 'Conecta Sur',
    organizacion: 'Estrellas del Sur',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: 15322,
    importeConcedido: null,
    leccion: 'Doce meses con doce días de coach y costes excepcionales. Ojo al cupo autonómico de Andalucía en la ronda de octubre.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Conecta_Sur_EstrellasDelSur',
  },
  {
    id: 'chemsafe-esc30-r3',
    nombre: 'CHEMSAFE',
    organizacion: 'Étoiles de France',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'FR02',
    ronda: '2026 R3',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: 4800,
    importeConcedido: null,
    leccion: 'Reescritura presencial y con coach tras la ronda 1. Presupuesto pequeño y sin costes excepcionales porque en octubre la agencia francesa tiene poco dinero.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_ChemSafe_Etoiles',
  },
  {
    id: 'haro-queer-esc30-v2',
    nombre: 'Haro Queer',
    organizacion: 'Horizonte Rioja',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 81,
    nota: null,
    importePedido: 3201,
    importeConcedido: null,
    leccion: 'Reescrita tras la ronda 1. Cuatro meses y tres días de coach para caber en el cupo de La Rioja (3.316,90 EUR). La coach ya no trabaja con el público.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Haro_Queer_Horizonte',
  },

  // ── En preparación ────────────────────────────────────────────
  {
    id: 'euroagora-ka154',
    nombre: 'EuroÁgora',
    organizacion: 'Horizonte Rioja',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por decidir',
    fechaPresentacion: null,
    estado: 'preparacion',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Ciclo de debate juvenil con torneos y Memorando para decisores. Es el primer proyecto que coordina Horizonte (ya fue socia en Democracia sin barreras). Nunca presentarlo como continuación de DiáLogos.',
    carpeta: 'erasmus/KA154_EuroAgora_Horizonte',
  },
  {
    id: 'by-lot-eyf',
    nombre: 'By Lot, Not by Habit',
    organizacion: 'Estrellas del Sur',
    programa: 'Consejo de Europa',
    accion: 'EYF',
    agencia: 'Fundación Europea de la Juventud',
    ronda: '2026.C3.C',
    fechaPresentacion: '2026-09-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Panel ciudadano juvenil elegido por sorteo en Córdoba. Se evaluaron ocho conceptos en tres rondas antes de elegir.',
    carpeta: 'consejo_de_europa/EYF_2026_C3C_Federacion',
    porConfirmar: true,
  },

  // ── Con resultado ─────────────────────────────────────────────
  {
    id: 'haro-queer-esc30-v1',
    nombre: 'Haro Queer (ronda 1)',
    organizacion: 'Horizonte Rioja',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: { total: 60, criterios: [{ nombre: 'Relevancia', puntos: 25, max: 40 }, { nombre: 'Diseño', puntos: 25, max: 40 }, { nombre: 'Gestión', puntos: 10, max: 20 }] },
    importePedido: 6402,
    importeConcedido: null,
    leccion: 'Superó el umbral pero no se financió: INJUVE priorizó otros proyectos de La Rioja. Fallaron datos sin fuente, aliados sin nombre, coach con el público y una gestión genérica.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Haro_Queer_Horizonte',
  },
  {
    id: 'chemsafe-esc30-r1',
    nombre: 'ChemSafe Jeunes (ronda 1)',
    organizacion: 'Étoiles de France',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'FR02',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: { total: 57, criterios: [{ nombre: 'Relevancia', puntos: 18, max: 40 }, { nombre: 'Diseño', puntos: 26, max: 40 }, { nombre: 'Gestión', puntos: 13, max: 20 }] },
    importePedido: null,
    importeConcedido: null,
    leccion: 'Todo en línea y sin coach en un tema sensible. La agencia lo leyó como proyecto de la asociación y no del grupo de jóvenes, y echó en falta datos y socios con nombre.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_ChemSafe_Etoiles',
  },
  {
    id: 'frames-of-us-ka152',
    nombre: 'Frames of Us',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-12',
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: 33200,
    importeConcedido: null,
    leccion: 'Primer KA152 de la Federación: intercambio en Usera con fotovoz, teatro silencioso y cortometrajes. Sirve de referencia de estructura, nunca de frases.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'melilla-is-europe-ka155',
    nombre: 'Melilla is Europe',
    organizacion: 'Estrella del Rif',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-12',
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: 27474,
    importeConcedido: null,
    leccion: 'KA155 aprobado de referencia: respuestas de 4.000 a 5.000 caracteres. Sus mecanismos (buddy, Kolb, cuaderno de emergencia) ya están gastados para las demás.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'dialogos-ka154',
    nombre: 'DiáLogos Europeos',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por confirmar',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Debate juvenil en Córdoba y Toledo. La agencia la señaló por su parecido con D-EU-BATING: la originalidad frente a proyectos propios anteriores también cuenta.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'd-eu-bating',
    nombre: 'D-EU-BATING',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por confirmar',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Proyecto de participación coordinado por Estrellas del Sur en 2025.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'community-dance-experience',
    nombre: 'Community Dance Experience',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2023',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Formación en Madrid en 2023 coordinada por Estrellas del Sur.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'nest-ka153',
    nombre: 'NEST',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Primer KA153 aprobado de la Federación, anterior a Frames of Us.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'decide-con-informacion-esc30',
    nombre: 'Decide con Información',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: 'Por confirmar',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Proyecto de solidaridad de la Federación, en ejecución.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'democracia-sin-barreras-ka154',
    nombre: 'Democracia sin barreras',
    organizacion: 'Estrella del Rif',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por confirmar',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Proyecto de participación de Estrella del Rif con Horizonte Rioja como socia. Por eso Horizonte ya no es recién llegada al Programa.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'd-iberia-ting-ka154',
    nombre: 'D-iberia-ting Europe',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: null,
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    leccion: 'Resultado por conocer.',
    carpeta: null,
    porConfirmar: true,
  },
];
