// Candidaturas que la red ha presentado o está preparando, con su resultado.
// Se muestran en la pestaña "Candidaturas" del radar (/radar/).
//
// Este fichero es PÚBLICO (va al repositorio). Solo datos del proyecto: nada
// de nombres de participantes, PRN, teléfonos ni correos. Las solicitudes
// completas y las cartas originales viven en proyectos/, que es un
// repositorio privado aparte (proyectos/referencias/resultados/).
//
// Campos:
//   id               identificador único (kebab-case)
//   nombre           título del proyecto
//   organizacion     una de ORGANIZACIONES
//   programa         una de PROGRAMAS
//   accion           código de la acción (KA152, KA155, ESC30, EYF...)
//   agencia          agencia que evalúa (ES02 INJUVE, FR02...)
//   ronda            texto corto ("2026 R2")
//   fechaPresentacion  AAAA-MM-DD o null (si solo se conoce el mes, el día es orientativo)
//   estado           una de ESTADOS. 'reserva' = calidad suficiente pero sin presupuesto
//   notaEstimada     puntuación de nuestro evaluador simulado (0-100) o null
//   nota             resultado real: { total, criterios: [{ nombre, puntos, max }] } o null
//   importePedido    euros o null
//   importeConcedido euros o null
//   recorte          qué modificó la agencia al conceder (texto) o null
//   comentarios      observaciones de la agencia, condensadas pero fieles (texto) o null
//   leccion          qué aprendimos (una o dos frases)
//   carpeta          ruta dentro de proyectos/ (para la skill), o null
//   porConfirmar     true si algún dato está pendiente de confirmar

export const ORGANIZACIONES = [
  'Estrellas del Sur',
  'Federación Estrellas de Europa',
  'Étoiles de France',
  'Horizonte Rioja',
  'Estrella del Rif',
  'Estrella Magec',
];

export const PROGRAMAS = ['Erasmus+', 'Cuerpo Europeo de Solidaridad', 'Consejo de Europa'];

export const ESTADOS = ['preparacion', 'presentada', 'aprobada', 'reserva', 'rechazada'];

// Criterios oficiales por acción (Guide for Experts 2026), para pintar las barras.
export const CRITERIOS = {
  KA152: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA153: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA154: [['Relevancia', 30], ['Diseño', 40], ['Gestión', 30]],
  KA155: [['Relevancia', 40], ['Diseño', 40], ['Gestión', 20]],
  ESC30: [['Relevancia', 40], ['Diseño', 40], ['Gestión', 20]],
};

export const ULTIMA_ACTUALIZACION = '2026-10-03';

// Atajo para escribir notas con los pesos de cada acción.
const n = (accion, r, d, g) => ({
  total: r + d + g,
  criterios: [
    { nombre: 'Relevancia', puntos: r, max: CRITERIOS[accion][0][1] },
    { nombre: 'Diseño', puntos: d, max: CRITERIOS[accion][1][1] },
    { nombre: 'Gestión', puntos: g, max: CRITERIOS[accion][2][1] },
  ],
});

export const CANDIDATURAS = [
  // ── Ronda de octubre de 2026 (pendientes de resolución) ──────
  {
    id: 'real-ka152',
    nombre: 'Real or Rendered? Youth, AI and Disinformation',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 76,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Intercambio en Madrid con Ucrania y Siria. Con la misma solicitante que un KA152 aprobado, el verificador de originalidad cazó calcos: pasarlo siempre. Evaluador calibrado: 76 más o menos 6 (antes estimábamos 87). Pesa la sobrecarga de productos para seis días.',
    carpeta: 'erasmus/KA152_REAL_Federacion',
  },
  {
    id: 'cadres-communs-ka152',
    nombre: 'Cadres Communs. Youth Storytelling for Wellbeing and Belonging',
    organizacion: 'Étoiles de France',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'FR02',
    ronda: '2026 Session 2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 76,
    nota: null,
    importePedido: 44150,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Adaptación en francés de un KA152 aprobado a París y seis socias nuevas. Reescribir desde el contexto local, nunca traducir. Evaluador calibrado: 76 más o menos 6 (antes 86). Socios locales sin acuerdo firmado y días de viaje para un grupo que vive en París.',
    carpeta: 'erasmus/KA152_Cadres_Communs_Etoiles',
  },
  {
    id: 'ember-ka153',
    nombre: 'EMBER',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Consorcio de ocho socias. Varias versiones de borrador hicieron perder horas: el PDF del portal manda siempre sobre los borradores. Sin estimación calibrada: la única exportación del portal que tenemos (15 de septiembre) tenía la gestión vacía.',
    carpeta: 'erasmus/KA153_EMBER_EstrellasDelSur',
  },
  {
    id: 'rutas-de-barrio-ka155',
    nombre: 'Rutas de Barrio',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 78,
    nota: null,
    importePedido: 19096,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'DiscoverEU con jóvenes de Usera y Villaverde. La primera versión se quedó corta (respuestas de 1.300 a 2.000 caracteres); se amplió a 4.000-4.900. Evaluador calibrado: 78 más o menos 6; riesgo de que financien un solo viaje, como a Melilla.',
    carpeta: 'erasmus/KA155_Rutas_de_Barrio_Federacion',
  },
  {
    id: 'billets-d-europe-ka155',
    nombre: "Billets d'Europe",
    organizacion: 'Étoiles de France',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'FR02',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 66,
    nota: null,
    importePedido: 22814,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'DiscoverEU en francés hacia España y Portugal. También se amplió: el KA155 aprobado de referencia tiene 4.000-5.000 caracteres por respuesta. Evaluador calibrado: 66 más o menos 6 sobre el texto con huecos sin rellenar; si se completaron en el portal, la nota real debería ser mayor.',
    carpeta: 'erasmus/KA155_Billets_d_Europe_Etoiles',
    porConfirmar: true,
  },
  {
    id: 'orgullo-de-pueblo-ka155',
    nombre: 'Orgullo de Pueblo',
    organizacion: 'Horizonte Rioja',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 80,
    nota: null,
    importePedido: 19234,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Jóvenes LGTBIQ+ rurales con viajes al Coming Out Day y al IDAHOBIT. Un verificador específico de protección evitó riesgos de exposición. Evaluador calibrado: 80 más o menos 6 (antes 88); riesgo de un solo viaje por ser entidad nueva.',
    carpeta: 'erasmus/KA155_Orgullo_de_Pueblo_Horizonte',
  },
  {
    id: 'conecta-sur-esc30',
    nombre: 'Conecta Sur',
    organizacion: 'Estrellas del Sur',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 81,
    nota: null,
    importePedido: 15322,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Doce meses con doce días de coach y costes excepcionales. Ojo al cupo autonómico de Andalucía en la ronda de octubre. Evaluador calibrado: 81 más o menos 6. Revisar que no se pegaran en el portal notas de edición (SUSTITUCION 1).',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Conecta_Sur_EstrellasDelSur',
  },
  {
    id: 'chemsafe-esc30-r3',
    nombre: 'CHEMSAFE',
    organizacion: 'Étoiles de France',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'FR02',
    ronda: '2026 R3',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 78,
    nota: null,
    importePedido: 4800,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Reescritura presencial y con coach tras la ronda 1. Presupuesto pequeño y sin costes excepcionales porque en octubre la agencia francesa tiene poco dinero. Evaluador calibrado: 78 más o menos 6 (la ronda 1 sacó 57).',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_ChemSafe_Etoiles',
  },
  {
    id: 'haro-queer-esc30-v2',
    nombre: 'Haro Queer',
    organizacion: 'Horizonte Rioja',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R2',
    fechaPresentacion: '2026-10-01',
    estado: 'presentada',
    notaEstimada: 80,
    nota: null,
    importePedido: 3201,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Reescrita tras la ronda 1. Cuatro meses y tres días de coach para caber en el cupo de La Rioja (3.316,90 EUR). La coach ya no trabaja con el público. Evaluador calibrado: 80 más o menos 6 (la ronda 1 sacó 60).',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Haro_Queer_Horizonte',
  },

  // ── En preparación ────────────────────────────────────────────
  {
    id: 'euroagora-ka154',
    nombre: 'EuroÁgora',
    organizacion: 'Horizonte Rioja',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por decidir',
    fechaPresentacion: null,
    estado: 'preparacion',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Ciclo de debate juvenil con torneos y Memorando para decisores. Es el primer proyecto que coordina Horizonte (ya fue socia en Democracia sin barreras). Nunca presentarlo como continuación de DiáLogos. Ojo: INJUVE ha leído dos veces los torneos de debate como ámbito académico y no como trabajo juvenil (Conexión Atlántica 52, D-iberia-ting 45).',
    carpeta: 'erasmus/KA154_EuroAgora_Horizonte',
  },
  {
    id: 'by-lot-eyf',
    nombre: 'By Lot, Not by Habit',
    organizacion: 'Estrellas del Sur',
    programa: 'Consejo de Europa',
    accion: 'EYF',
    agencia: 'Fundación Europea de la Juventud',
    ronda: '2026.C3.C',
    fechaPresentacion: '2026-09-01',
    estado: 'presentada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Panel ciudadano juvenil elegido por sorteo en Córdoba. Se evaluaron ocho conceptos en tres rondas antes de elegir.',
    carpeta: 'consejo_de_europa/EYF_2026_C3C_Federacion',
    porConfirmar: true,
  },

  // ── Ronda de febrero de 2026 (resuelta en septiembre de 2026) ─
  {
    id: 'democracia-sin-barreras-ka154',
    nombre: 'Democracia sin barreras',
    organizacion: 'Estrella del Rif',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'aprobada',
    notaEstimada: null,
    nota: { total: 80, criterios: [] },
    importePedido: 49416,
    importeConcedido: 26706,
    recorte: 'De 10 a 8 meses para limitar los gastos de gestión. Se elimina la actividad de Valencia y se mantiene el encuentro de Getafe por su vínculo con el Ayuntamiento, con 20 participantes (10 con menos oportunidades).',
    comentarios: 'Propuesta de alta calidad técnica y relevancia estratégica, con correlación sólida entre los objetivos de participación ciudadana y una metodología de aprendizaje no formal adaptada mediante Lectura Fácil y Diseño Universal para el Aprendizaje. Se valora especialmente la solvencia del consorcio, que combina entidades de referencia en discapacidad con la capacidad de incidencia y la capilaridad territorial de redes juveniles, bajo una gobernanza horizontal que sitúa a los jóvenes como cocreadores. No obstante, se detecta una ambición operativa que podría comprometer la viabilidad administrativa por la dispersión de recursos entre múltiples frentes, lo que motiva el ajuste presupuestario para priorizar la calidad de la inclusión y la sostenibilidad del Observatorio Juvenil de Barreras frente a la cantidad de acciones.',
    leccion: 'La mejor nota de la red en INJUVE (80 sobre 100) y aun así recortada casi a la mitad por "ambición operativa". Lo que salvó el encuentro de Getafe fue el vínculo institucional con el Ayuntamiento.',
    carpeta: 'referencias/resultados/2026-1/estrella_del_rif',
  },
  {
    id: 'melilla-is-europe-ka155',
    nombre: 'Melilla is Europe',
    organizacion: 'Estrella del Rif',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'aprobada',
    notaEstimada: null,
    nota: { total: 79, criterios: [] },
    importePedido: 27474,
    importeConcedido: 9158,
    recorte: 'Al tratarse de una organización nueva y con un proyecto ambicioso, se suprime uno de los tres viajes. La carta concede 9.158 euros de los 27.474 pedidos.',
    comentarios: 'Adecuada alineación con los objetivos de DiscoverEU Inclusión y sólido análisis de las necesidades de las personas jóvenes de Melilla, con relación clara entre estas, los objetivos del proyecto y los valores de la Unión Europea. Se valora positivamente la definición del grupo destinatario, el proceso de selección, la planificación de las fases y el impacto previsto en participantes y entorno local. La candidatura mejoraría con mayor concreción del itinerario y de los aspectos prácticos de la ejecución, especialmente al solicitar tres movilidades.',
    leccion: 'KA155 aprobado de referencia (79): respuestas de 4.000 a 5.000 caracteres y diagnóstico del territorio muy sólido. Sus mecanismos (buddy, Kolb, cuaderno de emergencia) ya están gastados para las demás. Tres viajes fueron demasiados para una entidad nueva.',
    carpeta: 'referencias/resultados/2026-1/estrella_del_rif',
  },
  {
    id: 'frames-of-us-ka152',
    nombre: 'Frames of Us',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'aprobada',
    notaEstimada: null,
    nota: { total: 72, criterios: [] },
    importePedido: 33200,
    importeConcedido: 29082,
    recorte: 'Se reduce el intercambio a 6 días de actividad más 2 de viaje por disponibilidad presupuestaria y el elevado número de solicitudes con calidad suficiente. Al grupo español se le resta un día de viaje en apoyo individual, porque todos los participantes son de Madrid.',
    comentarios: 'Reúne los requisitos de calidad y se ajusta a los objetivos del Programa y a las características de un intercambio juvenil. Participa junto a cinco entidades juveniles de Chequia, Portugal, Chipre, Polonia y Grecia, homogéneas y orientadas al trabajo juvenil; cuatro de las seis tienen bastante o mucha experiencia en el Programa. El objetivo (fortalecer la conexión entre bienestar, identidad personal y participación activa mediante metodologías creativas e inclusivas de educación no formal) es coherente con los valores del Programa. Se contempla adecuadamente el impacto en las organizaciones participantes y se consideran suficientes las medidas de impacto local, regional y europeo.',
    leccion: 'Primer KA152 de la Federación: intercambio en Usera con fotovoz, teatro silencioso y cortometrajes. Aprobado con 72, el más justo de los aprobados, y recortado un día. Sirve de referencia de estructura, nunca de frases.',
    carpeta: 'referencias/resultados/2026-1/federacion',
  },
  {
    id: 'decide-con-informacion-esc30',
    nombre: 'Decide con Información',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'aprobada',
    notaEstimada: null,
    nota: { total: 68, criterios: [] },
    importePedido: null,
    importeConcedido: 4461,
    recorte: null,
    comentarios: 'Pertinente como proyecto solidario del Cuerpo Europeo de Solidaridad, con la necesidad bien justificada y un diseño de calidad, objetivos claros y coherentes con las actividades; la composición del grupo es diversa y su experiencia se considera adecuada para alcanzar los objetivos.',
    leccion: 'ESC30 de la Federación aprobado con 68 y 4.461 euros. Grupo diverso y necesidad justificada: justo lo que las agencias echaron en falta en ChemSafe y Haro Queer.',
    carpeta: 'referencias/resultados/2026-1/federacion',
  },
  {
    id: 'debatia-2026-ka154',
    nombre: 'DebatIA: Europa frente a la Inteligencia Artificial',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'reserva',
    notaEstimada: null,
    nota: n('KA154', 24, 21, 15),
    importePedido: 45450,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Obtiene la calidad suficiente pero no accede a subvención por limitaciones presupuestarias. Se reconoce que se tuvieron en cuenta algunas observaciones de la ronda anterior, como eliminar el criterio de selección por perfil universitario. Pero se mantiene una orientación de la difusión hacia la atracción de talento y el prestigio académico, que no corresponde a esta acción y contrasta con el carácter abierto declarado. Hay escasas novedades respecto a la ronda anterior (mismo consorcio, fin, plan de acción y duración, con ajustes menores de presupuesto y la incorporación de participantes con menos oportunidades). Muchos datos confusos e inconsistentes: 3 o 5 fases según el apartado, actividades de 2 o 3 días, una tercera movilidad (visita al Congreso de los Diputados) en el calendario que no está registrada ni presupuestada, textos repetidos o que no responden a lo que se pregunta, y una implicación de los jóvenes en la planificación que no queda acreditada: parecen receptores de las actividades.',
    leccion: 'Segunda vez con 60 y sin fondos. La relevancia subió (24 de 30) pero la gestión se quedó en 15: incoherencias entre apartados, una movilidad sin presupuestar y un reenvío casi idéntico. Con 60 se compite por el cupo de Madrid contra proyectos de 70 y 80.',
    carpeta: 'referencias/resultados/2026-1/federacion',
  },
  {
    id: 'haro-queer-esc30-v1',
    nombre: 'Haro Queer (ronda 1)',
    organizacion: 'Horizonte Rioja',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'reserva',
    notaEstimada: null,
    nota: n('ESC30', 25, 25, 10),
    importePedido: 6402,
    importeConcedido: null,
    recorte: null,
    comentarios: 'La iniciativa se considera relevante en cuanto a su contenido, adecuada en su diseño y correcta en su propuesta de gestión. No obstante, se ha decidido priorizar otros proyectos presentados en la Comunidad de La Rioja que alcanzan un mayor nivel de calidad. Supera la puntuación mínima, pero por la alta concurrencia y las limitaciones presupuestarias se deniega.',
    leccion: 'Superó el umbral pero no se financió: INJUVE priorizó otros proyectos de La Rioja. Fallaron datos sin fuente, aliados sin nombre, coach con el público y una gestión genérica (10 de 20).',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_Haro_Queer_Horizonte',
  },
  {
    id: 'green-tracks-2026-ka155',
    nombre: 'European Green Tracks for Employability',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA155', 23, 23, 12),
    importePedido: 31568,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Enfoque pertinente que combina el empleo verde y la inclusión de jóvenes con menos oportunidades. Requiere mayor concreción en la definición de las entidades o socios colaboradores y una mejor justificación de la dimensión del proyecto y de la realización de cuatro movilidades independientes. Estas debilidades afectan a la viabilidad, la coherencia y el impacto, y la candidatura no alcanza el umbral mínimo.',
    leccion: 'Reenvío del KA155 que en 2025 sacó 61 sin fondos: en 2026 bajó a 58 y la gestión cayó a 12 de 20. Cuatro movilidades independientes y socios sin nombre. Repetir sin cambiar el diseño no sube la nota.',
    carpeta: 'referencias/resultados/2026-1/estrellas_del_sur',
  },
  {
    id: 'digite-ka153',
    nombre: 'DigiTE. Digital Tools for Empowerment',
    organizacion: 'Estrella Magec',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA153', 17, 20, 20),
    importePedido: 39099,
    importeConcedido: null,
    recorte: null,
    comentarios: 'La entidad debería explicar de manera más precisa su capacidad técnica y operativa, los trabajadores en el ámbito de la juventud de su organización y su intervención en la juventud local, concretando las actividades habituales, ejemplos de proyectos previos o resultados alcanzados. El proyecto es relevante para las prioridades de Erasmus+ (inclusión, transformación digital y trabajo con jóvenes migrantes) y para los objetivos de la movilidad de trabajadores en el ámbito de la juventud, con una temática de gran actualidad, pero se observan debilidades que disminuyen la calidad de la propuesta.',
    leccion: 'KA153 de Magec sobre herramientas digitales, a 3 puntos del umbral (17/20/20). Igual que en Igualdad y Deporte 2025, la relevancia cae porque no se acredita el trabajo juvenil local de la entidad: actividades habituales, equipo y resultados previos.',
    carpeta: 'referencias/resultados/2026-1/estrella_magec',
  },
  {
    id: 'chemsafe-esc30-r1',
    nombre: 'ChemSafe Jeunes (ronda 1)',
    organizacion: 'Étoiles de France',
    programa: 'Cuerpo Europeo de Solidaridad',
    accion: 'ESC30',
    agencia: 'FR02',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('ESC30', 18, 26, 13),
    importePedido: 3780,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Temática sensible y poco tratada, con enfoque de reducción de riesgos, objetivos claros y recursos digitales que pueden perdurar. Pero el análisis de necesidades se apoya en constataciones generales y en la experiencia declarada, sin datos ni metodología; no se precisa el vínculo entre la estructura y el público; los socios locales no se nombran; el compromiso de los jóvenes parece limitado y el proyecto se lee más como iniciativa de la asociación que de un grupo de jóvenes; el dispositivo totalmente digital no se justifica frente a la accesibilidad y la inclusión, y no hay coach pese a la sensibilidad del tema y la juventud de la entidad. Recomendaciones: perfiles y roles de los jóvenes, necesidades con método (consulta a jóvenes, datos, actores especializados), socios locales de prevención y salud, más participación de los beneficiarios y expertos en la temática.',
    leccion: 'Todo en línea y sin coach en un tema sensible. La agencia lo leyó como proyecto de la asociación y no del grupo de jóvenes, y echó en falta datos y socios con nombre.',
    carpeta: 'cuerpo_europeo_solidaridad/ESC30_ChemSafe_Etoiles',
  },
  {
    id: 'mind-the-gap-2026-ka152',
    nombre: 'Mind the Gap. Youth, Work & Well-Being',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA152', 18, 21, 15),
    importePedido: 33630,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Temática pertinente (bienestar, salud mental y empleabilidad). La justificación resulta extensa y algo sobredimensionada, con referencias muy amplias a estrategias y datos europeos pero menor concreción sobre las necesidades reales del grupo participante. El diseño tiene una secuencia metodológica clara, pero la propuesta resulta muy ambiciosa para un KA152, con demasiados productos, indicadores y acciones de difusión, y supera el máximo operativo de 30 personas. La gestión está ampliamente descrita pero resulta excesivamente compleja y con indicadores poco realistas; la difusión se apoya en objetivos de alcance digital muy elevados y el partenariado, aunque experimentado, presenta una estructura pesada para un intercambio juvenil.',
    leccion: 'Segundo intento (51 en 2025, 54 en 2026). La carta describe el fallo típico de la red: mucho texto europeo, poco grupo concreto, demasiados productos y más de 30 personas.',
    carpeta: 'referencias/resultados/2026-1/estrellas_del_sur',
  },
  {
    id: 'debate2participate-ka153',
    nombre: 'Debate2Participate. Critical Thinking, Media & Civic Engagement',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA153', 15, 22, 15),
    importePedido: 31771,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Temática pertinente que encaja formalmente en la tipología. La justificación de necesidades, el impacto esperado y la sostenibilidad se formulan de manera amplia y poco verificable. Aunque el diseño incorpora fases, metodologías y herramientas adecuadas, muchas medidas carecen de concreción operativa, indicadores sólidos y adaptación específica. La gestión del consorcio, la evaluación y la distribución de responsabilidades no ofrecen garantías suficientes.',
    leccion: 'Relevancia justo en la mitad (15 de 30). "Amplia y poco verificable" es la frase que resume el problema de justificación.',
    carpeta: 'referencias/resultados/2026-1/estrellas_del_sur',
  },
  {
    id: 'conexion-atlantica-ka154',
    nombre: 'Europa y Juventud: Conexión Atlántica',
    organizacion: 'Estrella Magec',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA154', 16, 20, 16),
    importePedido: 44150,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Conexión reconocible con las prioridades de participación democrática y las Metas Europeas de la Juventud, pero el diseño responde más a la lógica formativo-académica que a los objetivos de las Actividades de Participación Juvenil: los torneos de debate en entornos universitarios no acreditan su conexión con el trabajo juvenil no formal y las necesidades de las ocho entidades no justifican la intervención. No se explica cómo los beneficios del debate llegan a jóvenes de las comunidades locales. La inclusión no describe criterios de selección ni medidas de apoyo. Las dos movilidades (Tenerife y Toledo) aparecen como torneos aislados sin hilo conductor; el diálogo con responsables políticos cita genéricamente "eurodiputados, diputados nacionales o funcionarios" sin interlocutores reales; no se prevé colaboración con asociaciones juveniles, el Consejo de la Juventud de Canarias ni las universidades canarias; la logística es excesivamente genérica.',
    leccion: 'La carta más detallada que hemos recibido: torneos universitarios leídos como ámbito académico, decisores sin nombre y cero red territorial. Aplica a cualquier KA154 de debate de la red.',
    carpeta: 'referencias/resultados/2026-1/estrella_magec',
  },
  {
    id: 'semillas-de-cambio-ka152',
    nombre: 'Semillas de Cambio',
    organizacion: 'Horizonte Rioja',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA152', 16, 19, 16),
    importePedido: 34048,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Algunos objetivos del Programa solo se abordan de forma secundaria. La participación paritaria por sexos no se menciona de forma expresa. No hay una descripción clara de la justificación ni de cómo se identificó la necesidad, más allá de una mención genérica al cuidado del medio ambiente, ni de las necesidades de los participantes individuales más allá de su número. No se aprecia la relación directa entre los objetivos del Programa y las actividades, ni una programación que tenga impacto efectivo sobre el problema descrito. Parece excesivo el número de socias y participantes (36 personas de siete países) para solo seis días, y no está justificada la selección de entidades cuyo ámbito no está relacionado con el medio ambiente.',
    leccion: 'Primera solicitud propia de Horizonte. Siete países y 36 personas en seis días, socias sin relación con el tema y sin mención expresa de la paridad.',
    carpeta: 'referencias/resultados/2026-1/horizonte_rioja',
  },
  {
    id: 'd-iberia-ting-ka154',
    nombre: 'D-iberia-ting Europe',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA154', 15, 17, 13),
    importePedido: 50431,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Aborda ámbitos pertinentes (participación juvenil, debate democrático, alfabetización mediática). Las principales debilidades son una justificación apoyada en datos generales y en experiencias previas de la propia red, sin acreditar una demanda amplia fuera de los clubes de debate; un diseño ambicioso; una gestión del consorcio que requiere mayor concreción; y un impacto posterior, continuidad de la red ibérica y explotación de resultados no garantizados.',
    leccion: 'La nota más baja de la red en INJUVE (45) con el presupuesto más alto pedido (50.431). Justificar con la experiencia de la propia red no es acreditar demanda.',
    carpeta: 'referencias/resultados/2026-1/estrellas_del_sur',
  },
  {
    id: 'cap-ka153-fr02',
    nombre: "Compétences d'Autonomie et de Planification (CAP)",
    organizacion: 'Étoiles de France',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'FR02',
    ronda: '2026 R1',
    fechaPresentacion: '2026-02-18',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA153', 5, 10, 5),
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Temática pertinente (alfabetización financiera de los trabajadores juveniles), pero el análisis de necesidades es poco sólido, sin datos ni elementos concretos del territorio; incoherencias entre países socios, países de origen de los participantes y composición del consorcio; una estructura de creación muy reciente que reclama mucha actividad sin pruebas verificables; socias y miembros del equipo no identificables. El programa de formación es una lista de herramientas sin articulación pedagógica, con cifras de participantes que varían entre secciones y pasajes en forma de notas o borrador. La gestión asigna tareas a estructuras que no están en el consorcio, la logística es casi inexistente y la evaluación y la difusión son declarativas.',
    leccion: 'La peor nota de la red (20 sobre 100). Un borrador presentado como solicitud: incoherencias, frases incompletas y socias que no se pueden verificar. FR02 castiga la credibilidad antes que el contenido.',
    carpeta: 'referencias/resultados/2026-1/etoiles_de_france',
  },

  // ── Ronda de octubre de 2025 ──────────────────────────────────
  {
    id: 'debatia-2025-ka154',
    nombre: 'DebatIA: Europa frente a la Inteligencia Artificial (2025)',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'reserva',
    notaEstimada: null,
    nota: n('KA154', 20, 20, 20),
    importePedido: 38292,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Obtiene la calidad suficiente pero no accede a subvención por limitaciones presupuestarias. Iniciativa ambiciosa con enfoque formativo sólido para 87 jóvenes universitarios de 18 a 24 años junto a nueve socias universitarias; la implicación de altos responsables de la administración y académicos aporta rigor. Debilidades: la selección no contempla perfiles con menos oportunidades y se desconoce cómo se forman los equipos de debate; la sección de prácticas sostenibles no se corresponde con su contenido (herramientas digitales); la difusión y la visibilidad de la financiación de la UE podrían reforzarse; la afirmación de que solo universitarios "excelentes" tienen la madurez necesaria carece de evidencia y limita la inclusividad.',
    leccion: 'Veinte en cada criterio: suficiente en todo, bueno en nada. La frase sobre los universitarios "excelentes" es el ejemplo de lo que nunca se escribe en una solicitud de juventud.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'verde-y-claro-ka154',
    nombre: 'Verde y Claro. La Juventud Andaluza Debate el Futuro Climático de Europa',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA154', 20, 24, 15),
    importePedido: 33860,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Aborda de manera coherente sostenibilidad y participación juvenil con una planificación metodológica adecuada, pero carece de indicadores claros y de mecanismos sólidos de seguimiento y evaluación. Su proyección transnacional es escasa y la difusión poco desarrollada, lo que reduce el valor añadido europeo. La innovación es limitada y la sostenibilidad no garantiza la continuidad. Dado que la entidad recibió financiación en la ronda anterior para una iniciativa similar, se considera prioritario destinar los recursos a propuestas nuevas con enfoques más novedosos.',
    leccion: 'INJUVE penaliza repetir fórmula con la misma entidad: "ya recibió financiación en la ronda anterior para una iniciativa similar". La originalidad frente a los proyectos propios también puntúa.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'ecovibe-ka152',
    nombre: 'EcoVibe: Green up!',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA152', 19, 21, 18),
    importePedido: 43866,
    importeConcedido: null,
    recorte: null,
    comentarios: 'El proyecto es inspirador y relevante, pero necesita mayor concreción metodológica. La reducción de participantes contribuiría a optimizar los costes y garantizar la consistencia financiera del proyecto.',
    leccion: 'A dos puntos del umbral. La agencia pide dos cosas: método concreto y menos participantes.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'mind-the-gap-2025-ka152',
    nombre: 'Mind the Gap: Youth, Work & Well-Being (2025)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA152', 17, 18, 16),
    importePedido: 31440,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Enfoque pertinente, aunque la formulación de objetivos y su conexión con los resultados son limitadas. Falta concreción en la justificación y en la relevancia a nivel europeo. El itinerario pedagógico adolece de falta de coherencia global, la secuencia de aprendizaje no está claramente definida y los mecanismos de evaluación son insuficientes. El consorcio muestra diversidad geográfica y motivación, pero sin una estructura sólida de gestión; los mecanismos de seguimiento, comunicación y control de calidad son sustancialmente mejorables.',
    leccion: 'Primera versión de Mind the Gap, 51 puntos. Se volvió a presentar en febrero de 2026 con 54.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'rethink-redress-ka152',
    nombre: 'Re-Think, Re-Dress, Re-Love',
    organizacion: 'Estrella Magec',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA152', 20, 20, 19),
    importePedido: 50180,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Las fases están bien definidas, aunque no queda demostrada la participación activa de jóvenes con menos oportunidades en las distintas partes del proyecto, pese a la importancia con que se describen. Los métodos de aprendizaje (experiencial, trabajo en equipo, intercambio intercultural) quedan difusos en su aplicación. Seguridad correcta, actividades sostenibles y reconocimiento con Youthpass y el modelo Reconoce. El seguimiento (difusión, implicación comunitaria, mentoría) es generalista, sin concretar a qué entidades locales o municipios de la isla se dirige.',
    leccion: 'A un punto del umbral. Lo que faltó: menos oportunidades con papel activo visible y entidades locales con nombre en el seguimiento.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'igualdad-deporte-ka153',
    nombre: 'Fortaleciendo la Igualdad de Género a través del Poder del Deporte',
    organizacion: 'Estrella Magec',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: n('KA153', 15, 25, 19),
    importePedido: 39807,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Redacción muy correcta, fases bien descritas, actividades coherentes con los objetivos, Youthpass como herramienta central, prácticas sostenibles y herramientas virtuales; gestión, comunicación, difusión y sostenibilidad adecuadas. Pero no se detalla el impacto en la comunidad local, la necesidad no se concreta, el arraigo y el trabajo regular de la asociación en lo local no quedan explicados, no está claro cómo se transferirán los aprendizajes a otros trabajadores juveniles y a la organización, y el vínculo de los participantes con la solicitante no queda explicado.',
    leccion: 'Diseño de 25 y gestión de 19 tumbados por una relevancia de 15: sin arraigo local ni vínculo de los participantes con la entidad, un KA153 bien escrito no pasa.',
    carpeta: 'referencias/resultados/2025-3',
  },
  {
    id: 'nest-ka153',
    nombre: 'NEST',
    organizacion: 'Federación Estrellas de Europa',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R3',
    fechaPresentacion: '2025-10-01',
    estado: 'aprobada',
    notaEstimada: null,
    nota: { total: 70, criterios: [] },
    importePedido: null,
    importeConcedido: 24852,
    recorte: null,
    comentarios: null,
    leccion: 'Primer KA153 aprobado de la Federación (70 sobre 100, 24.852 euros), anterior a Frames of Us. Carta con comentarios pendiente de archivar.',
    carpeta: 'referencias/resultados/2025-3',
  },

  // ── Rondas anteriores ─────────────────────────────────────────
  {
    id: 'green-tracks-2025-ka155',
    nombre: 'European Green Tracks to Employability (2025)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA155',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R2',
    fechaPresentacion: null,
    estado: 'reserva',
    notaEstimada: null,
    nota: n('KA155', 23, 21, 17),
    importePedido: 31022,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Obtiene la calidad suficiente pero no accede a subvención por limitaciones presupuestarias. Buena intención educativa y social, pero su desarrollo carece de la coherencia y solidez necesarias para garantizar un impacto significativo. La gestión y las medidas de evaluación son poco precisas y ambiciosas para la capacidad de la entidad.',
    leccion: 'Primera versión del KA155 verde: 61 sin fondos. Al reenviarla en 2026 sin tocar el diseño bajó a 58.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'dialogos-2025-ka154',
    nombre: 'DiáLogos Europa',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2025 R1',
    fechaPresentacion: '2025-02-18',
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: 33598,
    recorte: 'Sin modificación presupuestaria.',
    comentarios: 'Proyecto muy bien articulado, con fuerte enfoque formativo, participación juvenil activa y proyección europea clara y sostenible.',
    leccion: 'Aprobado a la segunda, tras el rechazo de octubre de 2024. Debate juvenil en Córdoba y Toledo. La agencia la señaló luego por su parecido con D-EU-BATING: la originalidad frente a proyectos propios también cuenta.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'dialogos-2024-ka154',
    nombre: 'DiáLogos Europa (2024)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2024 R3',
    fechaPresentacion: '2024-10-01',
    estado: 'rechazada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Ciertas áreas de alineación con los objetivos del Programa, pero carece de elementos críticos en fundamentación, sostenibilidad y gestión de calidad. La insuficiencia de detalles en justificación, estructura y planificación limita su impacto. Si se vuelve a presentar, se recomienda reducir sensiblemente la cantidad solicitada, aparejada a una reducción sustancial del número de participantes.',
    leccion: 'La agencia dijo literalmente qué hacer: menos dinero y menos participantes. Se hizo y en febrero de 2025 se aprobó.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'd-eu-bating',
    nombre: 'D-EU-BATING',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: 'Por confirmar',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Proyecto de participación coordinado por Estrellas del Sur en 2025.',
    carpeta: null,
    porConfirmar: true,
  },
  {
    id: 'dialogos-2024r1-ka154',
    nombre: 'DiáLogos Europa (febrero de 2024)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA154',
    agencia: 'ES02 INJUVE',
    ronda: '2024 R1',
    fechaPresentacion: '2024-02-20',
    estado: 'rechazada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Pertinente a la acción y alineada con el Diálogo de la UE con la Juventud, pero con debilidades que impiden aprobarla: mejorar la relación de costes, más detalle y desarrollo en seguridad y protección, aclarar las medidas de calidad según los estándares Erasmus y la sostenibilidad de los resultados, y desarrollar la comunicación de resultados con implicación de los participantes.',
    leccion: 'Primer intento de DiáLogos. Tres rondas hasta la aprobación (febrero 2024, octubre 2024, febrero 2025); lo que cambió fue bajar coste y participantes, como pidió la segunda carta.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'turn-on-your-curiosity-ka152',
    nombre: 'Turn On Your Curiosity',
    organizacion: 'Estrella Magec',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2024 R1',
    fechaPresentacion: '2024-02-20',
    estado: 'rechazada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Las fases del proyecto resultan confusas y pueden concretarse mejor. No queda claro que los métodos estimulen la creatividad ni una participación más activa de los jóvenes. No se define la distribución de tareas ni la implicación de los jóvenes en ellas. La difusión y la evaluación son mejorables, y no queda claro cómo participarán los jóvenes del municipio donde se desarrolla.',
    leccion: 'Primer KA152 de Magec. Jóvenes del municipio sin papel definido: el mismo reproche que se repite en la red hasta 2026.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'becoming-european-citizens-2024',
    nombre: 'Becoming European Citizen (2024)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2024 R1',
    fechaPresentacion: '2024-02-20',
    estado: 'rechazada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'No se ajusta a los criterios de calidad de los intercambios juveniles. Recomienda mostrar cómo las actividades se alinean con los objetivos, indicadores concretos de impacto, más detalle en la programación de las etapas, actividades accesibles e inclusivas y un enfoque claro hacia las necesidades de los grupos menos favorecidos, más diversidad geográfica y de género, estrategias de seguridad y gestión de riesgos, prácticas sostenibles, identificar mejor la demanda y su relevancia para participantes y comunidades, abrirse a organizaciones nuevas, precisar las responsabilidades de cada socia y reforzar la evaluación y la difusión.',
    leccion: 'Segundo rechazo del mismo intercambio. La carta es una lista de casi todos los elementos de la rúbrica: señal de una solicitud genérica que no destaca en ninguno.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'becoming-european-citizens-2023',
    nombre: 'Becoming European Citizens (2023)',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA152',
    agencia: 'ES02 INJUVE',
    ronda: '2023 R3',
    fechaPresentacion: '2023-10-04',
    estado: 'rechazada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: 'Necesidades y objetivos pertinentes, pero la conexión con los objetivos y prioridades del Programa es limitada y no se liga a las actividades ni al método. El impacto en participantes es demasiado limitado y no se concreta por socia ni por territorio. Faltan descripciones claras de los perfiles, en especial de quienes tienen dificultades para acceder, y medidas específicas para su inclusión; el programa verde es limitado y no hay actividades definidas después de la movilidad. El equipo tiene experiencia y la logística es adecuada, pero los criterios del consorcio no convencen, no se explica cómo la coordinadora sigue las contribuciones de las socias, los indicadores no están claros y la sostenibilidad y la difusión necesitan acciones más concretas.',
    leccion: 'Primer KA152 propio presentado a INJUVE.',
    carpeta: 'referencias/resultados/2024-2025',
  },
  {
    id: 'community-dance-experience',
    nombre: 'Community Dance Experience',
    organizacion: 'Estrellas del Sur',
    programa: 'Erasmus+',
    accion: 'KA153',
    agencia: 'ES02 INJUVE',
    ronda: '2023',
    fechaPresentacion: null,
    estado: 'aprobada',
    notaEstimada: null,
    nota: null,
    importePedido: null,
    importeConcedido: null,
    recorte: null,
    comentarios: null,
    leccion: 'Formación en Madrid en 2023 coordinada por Estrellas del Sur.',
    carpeta: null,
    porConfirmar: true,
  },
];
