// Radar de subvenciones: datos de convocatorias relevantes para
// Estrellas del Sur (y pymes/autónomos del entorno).
//
// Cada entrada:
//   nombre        Nombre corto de la convocatoria
//   organismo     Quién convoca
//   ambito        'Córdoba' | 'Andalucía' | 'España' | 'Europa'
//   publico       ['asociaciones' | 'jóvenes' | 'pymes y autónomos' | 'entidades locales']
//   tematica      Frase corta
//   cuantia       Importe o rango (texto libre), '' si no se conoce
//   plazoInicio   'YYYY-MM-DD' o null
//   plazoFin      'YYYY-MM-DD' o null
//   estadoManual  null (se calcula por fechas) | 'prevista' | 'cerrada' | 'abierta'
//                 Si no es null, PREVALECE sobre las fechas (override manual).
//   estadoNota    Frase de contexto (cuándo suele salir, qué edición es...)
//   url           Enlace oficial
//   notas         Por qué nos interesa / a quién se lo mandamos
//   confianza     'alta' | 'media' | 'baja' (fiabilidad del dato a fecha de revisión)
//
// Investigación inicial: 2026-07-16, verificada en fuentes oficiales
// (BOJA, BOE, sedes electrónicas). Revisar plazos antes de solicitar.

export const ULTIMA_REVISION = '2026-07-16';

export const SUBVENCIONES = [
  // ── Córdoba ──────────────────────────────────────────────
  {
    nombre: 'IMDEEC ESAL 2026',
    organismo: 'IMDEEC · Ayuntamiento de Córdoba',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Desarrollo socioeconómico: congresos y jornadas (L1), empleabilidad e inserción sociolaboral (L2) y fortalecimiento del tejido con enfoque de género y juventud (L3)',
    cuantia: 'Dotación total 530.000 € (L1 60.000 · L2 320.000 · L3 150.000)',
    plazoInicio: '2026-07-06',
    plazoFin: '2026-07-20',
    estadoManual: null,
    estadoNota: 'Convocatoria 2026 abierta hasta el 20/07 a las 23:59. Suele salir cada año a principios de julio.',
    url: 'https://imdeec.es/ayudas-2026/',
    notas: 'Solicitable directamente por Estrellas del Sur como ESAL de Córdoba. La L2 (empleabilidad juvenil con prácticas) y la L3 (enfoque juventud) encajan. Presentación electrónica con certificado digital.',
    confianza: 'alta',
  },
  {
    nombre: 'Transforma Córdoba (Transformación Social)',
    organismo: 'Ayuntamiento de Córdoba · Servicios Sociales',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Proyectos de transformación social: inserción sociolaboral, convivencia intercultural, infancia, mayores y colectivos vulnerables',
    cuantia: 'Hasta 20.000 € por proyecto · dotación 700.000 € ampliable a 900.000 €',
    plazoInicio: '2025-12-31',
    plazoFin: '2026-01-22',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada y resuelta (27/04/2026). Se publica en BOP a final de año: vigilar diciembre de 2026 para la edición 2027 (plazo corto, 15 días hábiles).',
    url: 'https://www.cordoba.es/servicios/servicios-sociales/subvenciones/transformacion-social-2026',
    notas: 'La principal línea municipal de proyectos sociales. Encaja con inclusión o inserción sociolaboral de jóvenes ejecutada en Córdoba capital dentro del año natural.',
    confianza: 'alta',
  },
  {
    nombre: 'Fomento del Voluntariado Social',
    organismo: 'Ayuntamiento de Córdoba · Servicios Sociales',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Voluntariado social: actuaciones del Tercer Sector (L1) y promoción del voluntariado (L2)',
    cuantia: 'Dotación total 360.000 € (L1 240.000 · L2 120.000)',
    plazoInicio: '2026-01-09',
    plazoFin: '2026-01-29',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada y resuelta (27/04/2026). Se aprueba a final de diciembre con plazo en enero: anotar diciembre 2026 - enero 2027.',
    url: 'https://www.cordoba.es/servicios/servicios-sociales/subvenciones/proyectos-fomento-voluntariado-social-2026',
    notas: 'Muy afín a nuestro trabajo CES: la L2 financia específicamente proyectos que promuevan el voluntariado.',
    confianza: 'alta',
  },
  {
    nombre: 'Participación Ciudadana (Ayto. de Córdoba)',
    organismo: 'Ayuntamiento de Córdoba · Participación Ciudadana',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Participación y fortalecimiento del asociacionismo: proyectos (Mod. A) y gastos de funcionamiento de la entidad (Mod. B)',
    cuantia: 'Mod. A hasta 2.000 € · Mod. B hasta 3.500 € de funcionamiento · total 180.000 €',
    plazoInicio: '2025-11-07',
    plazoFin: '2025-11-26',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada y resuelta (01/06/2026). El plazo se abre en noviembre del año anterior: vigilar octubre-noviembre de 2026 para la edición 2027.',
    url: 'https://participa.cordoba.es/subvenciones/subvenciones-para-el-fomento-de-la-participacion-2026/',
    notas: 'La Modalidad B cubre gastos de funcionamiento (hasta 3.500 €), algo poco habitual. Requiere inscripción en el registro municipal de entidades ciudadanas.',
    confianza: 'alta',
  },
  {
    nombre: 'Participación Ciudadana (Diputación de Córdoba)',
    organismo: 'Diputación de Córdoba',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Proyectos de participación ciudadana en la provincia',
    cuantia: 'Hasta 2.000 € por proyecto (máx. 75% del presupuesto) · total 100.000 €',
    plazoInicio: '2026-04-27',
    plazoFin: '2026-05-18',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 18/05. Anual, suele publicarse en abril.',
    url: 'https://participacionciudadana.dipucordoba.es/convocatoria-de-subvenciones-a-asociaciones-que-desarrollen-proyectos-programas-y-actividades-de-participacion-ciudadana-en-la-provincia-de-cordoba-durante-el-ano-2026/',
    notas: 'Orientada a actividad en municipios de la provincia; revisar en las bases la elegibilidad de entidades con sede en la capital.',
    confianza: 'media',
  },
  {
    nombre: 'Somos Pueblo, Somos Cultura',
    organismo: 'Diputación de Córdoba · Cultura',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Proyectos culturales de iniciativa ciudadana en municipios de menos de 50.000 habitantes',
    cuantia: 'Dotación total 200.000 €',
    plazoInicio: '2026-04-21',
    plazoFin: '2026-05-12',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 12/05. Anual, suele abrirse en abril con 15 días hábiles.',
    url: 'https://cultura.dipucordoba.es/convocatorias-subvenciones-2026/',
    notas: 'Excluye Córdoba capital: serviría para actividades culturales nuestras en pueblos de la provincia.',
    confianza: 'alta',
  },
  {
    nombre: 'Ayudas Fundación Cajasur (Kutxabank)',
    organismo: 'Fundación Cajasur / Fundación Kutxabank',
    ambito: 'Córdoba',
    publico: ['asociaciones'],
    tematica: 'Acción e innovación social: inclusión, empleabilidad y fortalecimiento de entidades (incluye estructura y funcionamiento)',
    cuantia: 'Variable, por tandas periódicas del Patronato',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'abierta',
    estadoNota: 'Sin plazos: valoración continua, se solicita por contacto directo (info@fundacion.kutxabank.es · 957 214 333).',
    url: 'https://fundacionkutxabank.es/que_hacemos_social',
    notas: 'Priorizan proyectos innovadores y en colaboración; financian estructura básica de la entidad. Gestionan también el espacio Córdoba Social Lab.',
    confianza: 'media',
  },
  {
    nombre: 'IMDEEC Autoempleo 2026 (2º plazo)',
    organismo: 'IMDEEC · Ayuntamiento de Córdoba',
    ambito: 'Córdoba',
    publico: ['pymes y autónomos', 'jóvenes'],
    tematica: 'Creación de empresas y autoempleo en Córdoba capital',
    cuantia: 'Hasta 4.500 € (general) y 6.000 € (emprendimiento senior)',
    plazoInicio: '2026-09-25',
    plazoFin: '2026-10-09',
    estadoManual: null,
    estadoNota: 'Segundo periodo de solicitud del 25/09 al 09/10/2026 para empresas de nueva creación; el resto de líneas 2026 (Crece e Innova, Forma y Contrata) ya cerraron.',
    url: 'https://imdeec.es/ayudas-2026/',
    notas: 'Para difundir entre jóvenes que emprendan en Córdoba: cubre constitución, asesoría, marketing, alquiler y cuotas de Seguridad Social.',
    confianza: 'alta',
  },

  // ── Andalucía ────────────────────────────────────────────
  {
    nombre: 'Subvenciones 0,7% IRPF Andalucía',
    organismo: 'Consejería de Inclusión Social, Juventud, Familias e Igualdad (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['asociaciones'],
    tematica: 'Interés general y fines sociales: inclusión, voluntariado, juventud y colectivos vulnerables',
    cuantia: '49,5 M€ en las Líneas 1 y 2 de 2026 (más 13,7 M€ en las Líneas 3 y 4, ya cerradas)',
    plazoInicio: '2026-07-02',
    plazoFin: '2026-07-31',
    estadoManual: null,
    estadoNota: 'Líneas 1 (programas supraprovinciales) y 2 (obras) abiertas hasta el 31/07/2026. La Línea 4 (programas provinciales, nuestra vía natural) cerró el 22/06: prepararla para primavera de 2027.',
    url: 'https://www.juntadeandalucia.es/boja/2026/125/4.html',
    notas: 'El tramo autonómico del 0,7% es el más accesible para una entidad cordobesa. La L1 abierta exige ámbito supraprovincial o concurrir vía federación; requiere fines sociales en estatutos y registro de entidades.',
    confianza: 'alta',
  },
  {
    nombre: 'Subvenciones IAJ a asociaciones juveniles',
    organismo: 'Instituto Andaluz de la Juventud (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Juventud: sostenibilidad, empleabilidad, igualdad e inclusión, voluntariado, participación y cultura',
    cuantia: '291.000 €: Modalidad A provincial (máx. 25.000 € por provincia) y Modalidad B regional (91.000 €, actuación en 4+ provincias)',
    plazoInicio: '2026-03-09',
    plazoFin: '2026-04-06',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 06/04. Anual, sale en febrero-marzo: preparar la de 2027. No hay convocatorias provinciales separadas (Granada/Málaga gestionan el cupo provincial de la única convocatoria regional).',
    url: 'https://www.juntadeandalucia.es/boja/2026/45/3.html',
    notas: 'Nuestra línea autonómica principal. Requisito clave: estar inscritos en el Censo de Entidades de Participación Juvenil del IAJ antes de que se publique la convocatoria; verificar la inscripción ya.',
    confianza: 'alta',
  },
  {
    nombre: 'Innovactiva (emprendimiento juvenil)',
    organismo: 'Instituto Andaluz de la Juventud (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['jóvenes', 'pymes y autónomos'],
    tematica: 'Puesta en marcha de proyectos empresariales de jóvenes de 18 a 35 años',
    cuantia: 'Hasta 9.000 € por proyecto · total 407.386 €',
    plazoInicio: '2026-03-05',
    plazoFin: '2026-04-05',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 05/04. Anual, suele convocarse en marzo.',
    url: 'https://www.juntadeandalucia.es/organismos/inclusionsocialjuventudfamiliaseigualdad/servicios/actualidad/noticias/detalle/648082.html',
    notas: 'Para difundir entre antiguos voluntarios y participantes con proyecto de negocio: requiere titulación mínima, domicilio fiscal andaluz y gastos de puesta en marcha.',
    confianza: 'alta',
  },
  {
    nombre: 'Línea de voluntariado (Consejería de Inclusión Social)',
    organismo: 'Consejería de Inclusión Social, Juventud, Familias e Igualdad (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['asociaciones'],
    tematica: 'Promoción, sensibilización y formación del voluntariado (Línea 12 de la orden general de 16 líneas)',
    cuantia: 'Línea 12: 633.292 € · máx. 12.000 € por proyecto',
    plazoInicio: '2026-05-27',
    plazoFin: null,
    estadoManual: 'cerrada',
    estadoNota: 'Edición 2026 cerrada (15 días hábiles desde el 27/05, hasta mediados de junio). Se convoca anualmente hacia mayo-junio.',
    url: 'https://www.juntadeandalucia.es/boja/2026/99/c01/1',
    notas: 'Suele exigir inscripción en el Registro General de Entidades de Voluntariado de Andalucía: tener el trámite al día antes de la convocatoria 2027.',
    confianza: 'media',
  },
  {
    nombre: 'Voluntariado y participación en el ámbito educativo',
    organismo: 'Consejería de Desarrollo Educativo (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['asociaciones'],
    tematica: 'Voluntariado en actividades extraescolares, coeducación y equidad en centros educativos (curso 2026/2027)',
    cuantia: 'Línea de voluntariado: 120.000 €',
    plazoInicio: '2026-06-17',
    plazoFin: null,
    estadoManual: 'cerrada',
    estadoNota: 'Convocatoria del curso 2026/2027 cerrada a principios de julio. Anual, sale en junio.',
    url: 'https://www.juntadeandalucia.es/boja/2026/114/2.html',
    notas: 'Vía para talleres de interculturalidad y movilidad europea en institutos. Requiere inscripción en el Censo de Entidades Colaboradoras de la Enseñanza: preparar el trámite para concurrir en junio de 2027.',
    confianza: 'media',
  },
  {
    nombre: 'Proyectos Sociales Andalucía (Fundación la Caixa)',
    organismo: 'Fundación la Caixa, en colaboración con Fundación Cajasol',
    ambito: 'Andalucía',
    publico: ['asociaciones'],
    tematica: 'Inclusión social: pobreza, discapacidad y salud mental, mayores; transversales de interculturalidad e inserción sociolaboral',
    cuantia: 'Hasta 50.000 € por proyecto (cofinanciación propia mínima del 25%)',
    plazoInicio: '2026-04-09',
    plazoFin: '2026-05-14',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 14/05, resolución prevista en diciembre. Muy estable: prever abril de 2027.',
    url: 'https://fundacionlacaixa.org/es/convocatorias-sociales-descripcion',
    notas: 'La mayor obra social con línea territorial andaluza, en 2026 con Cajasol como socia y prioridad en pobreza infantil. Encaja con inclusión de jóvenes vulnerables (perfil NEET de nuestros voluntariados). Las convocatorias propias de Cajasol son premios y concursos.',
    confianza: 'alta',
  },
  {
    nombre: 'Incentivos TRADE a pequeñas empresas',
    organismo: 'Agencia TRADE (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['pymes y autónomos'],
    tematica: 'Creación y puesta en marcha de pequeñas empresas y microempresas (menos de 5 años)',
    cuantia: 'Hasta el 70% de la inversión · inversión mínima 30.000 € · presupuesto 7,5 M€',
    plazoInicio: '2024-07-10',
    plazoFin: '2027-12-30',
    estadoManual: null,
    estadoNota: 'Abierta en régimen no competitivo (orden de llegada) hasta el 30/12/2027 o agotar crédito.',
    url: 'https://one.gob.es/en/aid-and-calls/grants-promotion-start-projects-small-businesses-andalusia',
    notas: 'Para difundir a emprendedores del entorno; los CADE de Andalucía Emprende acompañan gratis la tramitación.',
    confianza: 'alta',
  },
  {
    nombre: 'Cuota Cero para nuevos autónomos',
    organismo: 'Consejería de Empleo (Junta de Andalucía)',
    ambito: 'Andalucía',
    publico: ['pymes y autónomos', 'jóvenes'],
    tematica: 'Reintegro de las cuotas de Seguridad Social del primer año (y segundo si los ingresos no superan el SMI) a nuevos autónomos con tarifa plana',
    cuantia: 'Devolución de las cuotas de 12 o 24 meses (tarifa plana estatal de 80 €/mes)',
    plazoInicio: '2024-01-02',
    plazoFin: '2026-09-30',
    estadoManual: null,
    estadoNota: 'Abierta de forma continua hasta el 30/09/2026; se solicita en los 2 meses siguientes a cumplir 12 meses con cuota reducida.',
    url: 'https://www.juntadeandalucia.es/organismos/empleoempresaytrabajoautonomo/areas/trabajo-autonomo/fomento-trabajo-autonomo/paginas/subv-fomento-cuota-cero.html',
    notas: 'Muy difundible entre jóvenes que se hagan autónomos: coste efectivo cero el primer año.',
    confianza: 'alta',
  },

  // ── España ───────────────────────────────────────────────
  {
    nombre: 'INJUVE: mantenimiento de asociaciones juveniles',
    organismo: 'INJUVE (Ministerio de Juventud e Infancia)',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Gastos de funcionamiento y mantenimiento del movimiento asociativo juvenil',
    cuantia: '1.362.760 € totales',
    plazoInicio: '2026-07-01',
    plazoFin: '2026-07-28',
    estadoManual: null,
    estadoNota: 'Convocatoria 2026 abierta hasta el 28/07 (solicitud por SIGES).',
    url: 'https://www.injuve.es/subvenciones-asociaciones-juveniles/noticia/convocatoria-subvenciones-injuve-2026',
    notas: 'Ojo: exige ámbito estatal según estatutos e implantación en varias comunidades. Valorar concurrir a través de una federación estatal o revisar estatutos antes de invertir tiempo.',
    confianza: 'alta',
  },
  {
    nombre: 'Subvenciones 0,7% IRPF (tramo estatal)',
    organismo: 'Ministerio de Derechos Sociales, Consumo y Agenda 2030',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Programas de interés social de ámbito estatal (atención a personas, inserción, modernización del Tercer Sector)',
    cuantia: '~108 M€ · programas de 20.000 € a 5 M€',
    plazoInicio: '2026-05-20',
    plazoFin: '2026-06-25',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 25/06 (plazo ampliado por incidencias en SIGES). Anual, sale en mayo.',
    url: 'https://www.boe.es/buscar/doc.php?id=BOE-B-2026-16237',
    notas: 'Solo entidades de ámbito estatal: nuestra vía realista es ir como ejecutantes dentro del programa de una confederación. Contactar federaciones estatales antes de la primavera de 2027. El esfuerzo directo conviene ponerlo en el tramo andaluz.',
    confianza: 'alta',
  },
  {
    nombre: 'Fundación ONCE: convocatoria general',
    organismo: 'Fundación ONCE',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Inclusión de personas con discapacidad: formación y creación de empleo, accesibilidad, autonomía personal',
    cuantia: 'Según tipo de proyecto',
    plazoInicio: '2026-01-26',
    plazoFin: '2026-06-30',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 30/06. Anual y estable: la siguiente abrirá a finales de enero de 2027.',
    url: 'https://www.fundaciononce.es/es/convocatorias-de-ayudas/para-entidades/convocatoria-general',
    notas: 'Relevante para proyectos de inclusión de jóvenes con discapacidad, línea transversal habitual en nuestros Erasmus+/CES. Solicitud sencilla por email.',
    confianza: 'alta',
  },
  {
    nombre: 'Ayudas a la acción y promoción cultural',
    organismo: 'Ministerio de Cultura',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Proyectos culturales que generan contenidos y modernizan el sector',
    cuantia: '',
    plazoInicio: '2026-01-21',
    plazoFin: '2026-02-11',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 11/02. Anual, se publica en enero.',
    url: 'https://www.cultura.gob.es/servicios-a-la-ciudadania/catalogo/general/05/055036/ficha/055036-2026.html',
    notas: 'Concurrencia alta y perfil profesional del sector cultural; posible encaje puntual para proyectos culturales propios.',
    confianza: 'alta',
  },
  {
    nombre: 'Certamen Nacional de Jóvenes Emprendedores',
    organismo: 'INJUVE (Ministerio de Juventud e Infancia)',
    ambito: 'España',
    publico: ['jóvenes', 'pymes y autónomos'],
    tematica: 'Premios a proyectos empresariales liderados por jóvenes (empresas de 1 a 3 años)',
    cuantia: '20.000 € para cada uno de los 10 premiados',
    plazoInicio: '2026-04-10',
    plazoFin: '2026-05-08',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada el 08/05. Anual, en primavera.',
    url: 'https://www.injuve.es/certamen-emprendedores/noticia/convocatoria-certamen-jovenes-emprendedores',
    notas: 'Para difundir entre jóvenes del entorno con negocio en marcha (hasta 35 años). INJUVE tiene también las Ayudas a la Creación Joven (3.000-10.000 €).',
    confianza: 'alta',
  },
  {
    nombre: 'Kit Digital',
    organismo: 'Red.es (Ministerio para la Transformación Digital)',
    ambito: 'España',
    publico: ['pymes y autónomos'],
    tematica: 'Bonos de digitalización: web, redes, ciberseguridad, IA, puesto de trabajo seguro',
    cuantia: 'Bonos de 3.000 € (autónomos y micro) a 12.000 € o más según segmento',
    plazoInicio: null,
    plazoFin: '2025-10-31',
    estadoManual: null,
    estadoNota: 'Sin plazo abierto: las convocatorias cerraron el 31/10/2025, pero la Orden TDF/39/2026 obliga a reinvertir remanentes, con posible reapertura aún sin fecha. Vigilar sede.red.gob.es.',
    url: 'https://www.kitdigital.red.es/convocatorias',
    notas: 'Cuando reabra con remanentes será lo primero que difundir a pymes y autónomos del entorno.',
    confianza: 'alta',
  },

  // ── Europa ───────────────────────────────────────────────
  {
    nombre: 'Erasmus+ Juventud · Ronda 2 (KA152/153/154)',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Intercambios juveniles, movilidad de trabajadores juveniles y participación',
    cuantia: '20% del presupuesto KA1 de 2026 (el 80% se repartió en la R1)',
    plazoInicio: null,
    plazoFin: '2026-10-01',
    estadoManual: null,
    estadoNota: 'Ronda 2 abierta hasta el 01/10/2026 a las 12:00 (hora de Bruselas). No hay R3 en juventud este año.',
    url: 'https://programaseuropeos.injuve.es/erasmus/erasmus-juventud-y-deporte-convocatoria-2026',
    notas: 'Nuestra ronda clave del otoño: proyectos que arrancan entre enero y mayo de 2027.',
    confianza: 'alta',
  },
  {
    nombre: 'CES · Proyectos Solidarios · Ronda 2',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['jóvenes', 'asociaciones'],
    tematica: 'Proyectos solidarios locales liderados por grupos de jóvenes',
    cuantia: '20% del presupuesto de la acción',
    plazoInicio: null,
    plazoFin: '2026-10-01',
    estadoManual: null,
    estadoNota: 'Ronda 2 abierta hasta el 01/10/2026 a las 12:00 (hora de Bruselas).',
    url: 'https://programaseuropeos.injuve.es/ces/cuerpo-europeo-de-solidaridad-convocatoria-2026',
    notas: 'Muy accesible para grupos de jóvenes de Córdoba con nuestro apoyo como coach. Coincide con la R2 de Erasmus+: prever la carga de septiembre.',
    confianza: 'alta',
  },
  {
    nombre: 'Erasmus+ · Acreditación juventud (KA150)',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Acreditación para acceso simplificado a la movilidad juvenil KA151',
    cuantia: 'No conlleva subvención directa (da acceso a fondos KA151 anuales)',
    plazoInicio: null,
    plazoFin: '2026-09-29',
    estadoManual: null,
    estadoNota: 'Plazo hasta el 29/09/2026 a las 12:00 (hora de Bruselas), convocatoria EAC/A12/2025.',
    url: 'https://programaseuropeos.injuve.es/erasmus/erasmus-juventud-y-deporte-convocatoria-2026',
    notas: 'Ya estamos acreditados; útil si se plantea acreditar a la federación Estrellas de Europa o asesorar a entidades del entorno.',
    confianza: 'media',
  },
  {
    nombre: 'CES · Sello de Calidad (Quality Label)',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Acreditación de entidades para voluntariado del Cuerpo Europeo de Solidaridad',
    cuantia: 'No conlleva subvención (acreditación)',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'abierta',
    estadoNota: 'Se puede solicitar en cualquier momento; para acceder a los fondos de la ronda de febrero de 2027 hay que presentarla antes del 29/10/2026.',
    url: 'https://programaseuropeos.injuve.es/ces/cuerpo-europeo-de-solidaridad-convocatoria-2026',
    notas: 'Ya lo tenemos; dato clave para entidades cordobesas a las que asesoremos.',
    confianza: 'alta',
  },
  {
    nombre: 'CERV · Hermanamiento de ciudades',
    organismo: 'Comisión Europea (EACEA)',
    ambito: 'Europa',
    publico: ['entidades locales', 'asociaciones'],
    tematica: 'Ciudadanía europea: encuentros entre ciudadanos de distintos países (proyectos de 6 a 12 meses)',
    cuantia: '8.500 a 50.700 € por proyecto · presupuesto 6 M€',
    plazoInicio: null,
    plazoFin: '2026-09-23',
    estadoManual: null,
    estadoNota: 'Abierta hasta el 23/09/2026 (CERV-2026-CITIZENS-TOWN-TT).',
    url: 'https://www.cultura.gob.es/cultura/areas/cooperacion/mc/pec/convocatorias.html',
    notas: 'Oportunidad realista para entidad pequeña, en alianza con el Ayuntamiento o un comité de hermanamiento; confirmar elegibilidad exacta en el Funding & Tenders Portal.',
    confianza: 'alta',
  },
  {
    nombre: 'CERV · Daphne (prevención de violencia)',
    organismo: 'Comisión Europea (EACEA)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Lucha contra la violencia hacia mujeres, infancia y juventud',
    cuantia: '',
    plazoInicio: null,
    plazoFin: '2026-11-03',
    estadoManual: null,
    estadoNota: 'Convocatoria 2026 abierta hasta el 03/11/2026 según el Punto Europeo de Ciudadanía.',
    url: 'https://www.cultura.gob.es/cultura/areas/cooperacion/mc/pec/convocatorias.html',
    notas: 'Suele exigir partenariado transnacional: entraríamos como socio más que como coordinador.',
    confianza: 'alta',
  },
  {
    nombre: 'CERV · Memoria histórica europea',
    organismo: 'Comisión Europea (EACEA)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Memoria histórica y valores de la Unión',
    cuantia: '',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'prevista',
    estadoNota: 'Apertura prevista en octubre de 2026 según el Punto Europeo de Ciudadanía; plazo exacto sin publicar.',
    url: 'https://www.cultura.gob.es/cultura/areas/cooperacion/mc/pec/convocatorias.html',
    notas: 'Vigilar la web del Punto Europeo de Ciudadanía a partir de octubre.',
    confianza: 'media',
  },
  {
    nombre: 'Erasmus+ Juventud · KA210 (cooperación)',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Asociaciones de cooperación a pequeña escala en juventud',
    cuantia: 'KA210: 30.000 o 60.000 € a tanto alzado por proyecto',
    plazoInicio: null,
    plazoFin: '2026-03-05',
    estadoManual: null,
    estadoNota: 'La ronda única de KA2 juventud 2026 cerró el 05/03. La convocatoria 2027 se publica en noviembre con plazo en marzo.',
    url: 'https://programaseuropeos.injuve.es/erasmus/erasmus-juventud-y-deporte-convocatoria-2026',
    notas: 'Preparar una KA210 propia de cara a marzo de 2027 (ya tenemos experiencia como socios en ConnectART y YouthConnect).',
    confianza: 'alta',
  },
  {
    nombre: 'CES · Proyectos de voluntariado (ESC51)',
    organismo: 'Comisión Europea · Agencia Nacional (INJUVE)',
    ambito: 'Europa',
    publico: ['asociaciones'],
    tematica: 'Fondos para proyectos de voluntariado individual y en equipo',
    cuantia: '100% del presupuesto de la acción en ronda única',
    plazoInicio: null,
    plazoFin: '2026-02-18',
    estadoManual: null,
    estadoNota: 'La ronda única 2026 cerró el 18/02. La convocatoria 2027 se publica en noviembre con plazo hacia febrero.',
    url: 'https://programaseuropeos.injuve.es/ces/cuerpo-europeo-de-solidaridad-convocatoria-2026',
    notas: 'Como entidad acreditada CES, planificar la solicitud de fondos 2027 en otoño de 2026.',
    confianza: 'alta',
  },

  // ── Fundaciones bancarias (fase 2, 2026-07-16) ──────────
  {
    nombre: 'Premios Ricardo López Crespo',
    organismo: 'Fundación Caja Rural del Sur',
    ambito: 'Córdoba',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Premios a la acción social solidaria, iniciativas empresariales de jóvenes, agroalimentación y patrimonio en la provincia de Córdoba',
    cuantia: '4.000 € por categoría principal, más estatuilla',
    plazoInicio: '2026-07-13',
    plazoFin: '2026-10-09',
    estadoManual: null,
    estadoNota: 'XVI edición abierta hasta el 09/10/2026; fallo antes del 31/01/2027. Se convoca cada verano.',
    url: 'https://fundacioncajaruraldelsur.com/',
    notas: 'Muy a nuestro alcance: la categoría Acción Social Solidaria encaja con nuestra labor y la de Jóvenes Emprendedores sirve para difundir. Candidaturas por email (la fundación es heredera de la obra social de Caja Rural de Córdoba).',
    confianza: 'alta',
  },
  {
    nombre: 'Convocatoria de Acción Social (Fundación Unicaja)',
    organismo: 'Fundación Unicaja',
    ambito: 'Andalucía',
    publico: ['asociaciones'],
    tematica: 'Inclusión social de colectivos vulnerables, con énfasis en infancia y juventud',
    cuantia: 'Más de 2 M€ entre 36 proyectos en 2026 (solicitudes de 10.000 a 100.000 € en la extraordinaria previa)',
    plazoInicio: '2025-10-15',
    plazoFin: '2025-11-14',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada y resuelta en marzo. Pauta anual: abre en octubre-noviembre; preparar candidatura para octubre de 2026.',
    url: 'https://www.fundacionunicaja.com/convocatoria-accion-social/',
    notas: 'Encaje alto: infancia y juventud es ámbito prioritario y cubre toda Andalucía. Solicitudes en proyectos.fundacionunicaja.com. En 2024 lanzó además convocatorias extraordinarias que podrían repetirse.',
    confianza: 'alta',
  },
  {
    nombre: 'Santander Ayuda',
    organismo: 'Fundación Banco Santander',
    ambito: 'España',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Proyectos educativos para infancia y adolescencia (0-18 años) en riesgo de pobreza o exclusión',
    cuantia: 'Hasta 20.000 € por proyecto',
    plazoInicio: '2025-11-25',
    plazoFin: '2025-12-18',
    estadoManual: null,
    estadoNota: 'Segunda edición cerrada. El programa pasó de microayudas trimestrales a ediciones anuales temáticas: vigilar otoño de 2026 para la tercera.',
    url: 'https://www.fundacionbancosantander.com/es/accion-social/santander-ayuda',
    notas: 'Encaje medio-alto si el proyecto se enfoca a adolescentes vulnerables con educación no formal.',
    confianza: 'media',
  },
  {
    nombre: 'Proyectos Sociales (Fundación Ibercaja)',
    organismo: 'Fundación Ibercaja',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Empleabilidad, acción social y educación para colectivos en riesgo de exclusión, alineado con los ODS',
    cuantia: 'Hasta 20.000 € por proyecto, sin superar la aportación propia de la entidad',
    plazoInicio: '2026-02-19',
    plazoFin: '2026-03-18',
    estadoManual: null,
    estadoNota: 'Edición 2026 (la 21ª) cerrada y resuelta. Anual: abre en febrero-marzo. Además mantiene abierta todo el año una Solicitud de Colaboración Económica fuera de convocatoria.',
    url: 'https://www.fundacionibercaja.es/convocatorias/convocatoria-2026-fundacion-ibercaja-de-proyectos-sociales-zaragoza/',
    notas: 'Abierta a entidades de todo el país con 2 años de antigüedad registral: ya cumplimos requisitos. La vía de colaboración continua es interesante como plan B flexible.',
    confianza: 'alta',
  },
  {
    nombre: 'Talento Solidario (Fundación Botín)',
    organismo: 'Fundación Botín',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'Fortalecimiento institucional de organizaciones sociales pequeñas y medianas: gestión, estrategia, digitalización',
    cuantia: 'Programa de 2 años con formación, mentoría, ayuda económica para servicios o personal y acceso a una red de 450+ entidades',
    plazoInicio: '2025-12-10',
    plazoFin: '2026-01-29',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada. Pauta muy estable: abre en diciembre y cierra a finales de enero; apuntar diciembre de 2026.',
    url: 'https://fundacionbotin.org/programas/fortalecimiento-del-sector-social/convocatoria-talento-solidario/',
    notas: 'Encaje muy bueno: no financia proyectos sino que profesionaliza la organización, justo lo que necesita una asociación en crecimiento.',
    confianza: 'alta',
  },
  {
    nombre: 'Ayudas a Proyectos Sociales (Fundación MAPFRE)',
    organismo: 'Fundación MAPFRE',
    ambito: 'España',
    publico: ['asociaciones'],
    tematica: 'En 2026, empleabilidad de personas con discapacidad intelectual o salud mental y enfermedades raras',
    cuantia: '500.000 € en 50 ayudas (unos 10.000 € por proyecto)',
    plazoInicio: null,
    plazoFin: '2026-04-24',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada y resuelta. Anual: abre a comienzos de año. Los focos temáticos cambian cada edición.',
    url: 'https://www.fundacionmapfre.org/premios-ayudas/convocatorias/convocatoria-ayudas-proyectos-sociales/',
    notas: 'Encaje bajo este año por el foco en discapacidad y enfermedades raras; vigilar los temas de la edición 2027.',
    confianza: 'media',
  },

  // ── Madrid (fase 2) ──────────────────────────────────────
  {
    nombre: 'Proyectos formativos y de sensibilización juvenil (CAM)',
    organismo: 'Comunidad de Madrid · Dirección General de Juventud',
    ambito: 'Madrid',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Formación y sensibilización para jóvenes, educación no formal y animación sociocultural',
    cuantia: 'Hasta 8.000 € por proyecto, máximo 70% del coste',
    plazoInicio: '2026-04-28',
    plazoFin: '2026-05-12',
    estadoManual: null,
    estadoNota: 'Edición 2026 cerrada. Anual con plazo en primavera; vigilar la orden equivalente de 2027.',
    url: 'https://sede.comunidad.madrid/ayudas-becas-subvenciones/formacion-sensibilizacion-entidades-0',
    notas: 'La línea núcleo de juventud madrileña. Exige actividad en la Comunidad de Madrid: haría falta delegación propia o socio madrileño.',
    confianza: 'alta',
  },
  {
    nombre: 'Campos de voluntariado juvenil (CAM)',
    organismo: 'Comunidad de Madrid · Consejería de Familia, Juventud y Asuntos Sociales',
    ambito: 'Madrid',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Campos de voluntariado juvenil: medio ambiente, patrimonio, acción comunitaria',
    cuantia: '',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'anunciar',
    estadoNota: 'La edición 2026 estaba pendiente de publicación a 16/07. Pauta anual con plazo en otoño: vigilar el BOCM en octubre.',
    url: 'https://sede.comunidad.madrid/ayudas-becas-subvenciones/subvencion-entidades-campos-voluntariado',
    notas: 'Muy alineada con nuestro perfil CES de voluntariado; exige actividad en la Comunidad de Madrid.',
    confianza: 'media',
  },
  {
    nombre: 'Fomento del asociacionismo (Ayto. de Madrid)',
    organismo: 'Ayuntamiento de Madrid · Vicealcaldía y Juntas de Distrito',
    ambito: 'Madrid',
    publico: ['asociaciones'],
    tematica: 'Asociacionismo y participación: proyectos y gastos de funcionamiento de sedes, por distritos',
    cuantia: '',
    plazoInicio: '2025-11-03',
    plazoFin: '2025-11-24',
    estadoManual: null,
    estadoNota: 'Convocatoria anticipada 2026 cerrada en noviembre de 2025. Anual, con convocatoria anticipada en otoño.',
    url: 'https://www.madrid.es/portales/munimadrid/es/Inicio/El-Ayuntamiento/Espacio-asociativo/Noticias-y-novedades/Convocatorias-publicas-de-subvenciones-de-fomento-del-asociacionismo-2025-2026-distritos/?vgnextoid=3f445491b57c5910VgnVCM1000001d4a900aRCRD&vgnextchannel=137742b32a131610VgnVCM1000001d4a900aRCRD',
    notas: 'Exige inscripción en el censo municipal y adscripción a un distrito: solo con implantación real en Madrid capital.',
    confianza: 'alta',
  },
  {
    nombre: 'Actividades infantil-juveniles y asociacionismo (Ayto. de Madrid)',
    organismo: 'Ayuntamiento de Madrid · Vicealcaldía',
    ambito: 'Madrid',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Ocio saludable, salud mental, convivencia y asociacionismo juvenil (proyectos bienales)',
    cuantia: '700.000 €/año (400.000 ocio saludable + 300.000 salud mental)',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'cerrada',
    estadoNota: 'Convocatoria bienal 2026-2027 ya cerrada (se publicó en diciembre de 2025); la próxima, previsiblemente a finales de 2027.',
    url: 'https://www.madrid.es/portales/munimadrid/es/Inicio/El-Ayuntamiento/Espacio-asociativo/Noticias-y-novedades/Convocatoria-publica-de-subvenciones-para-el-desarrollo-de-actividades-dirigidas-a-la-poblacion-infantil-y-juvenil-asi-como-a-la-mejora-de-la-convivencia-y-el-desarrollo-comunitario-mediante-la-promocion-de-la-participacion-y-el-asociacioni/?vgnextfmt=default&vgnextoid=be615b7687bba910VgnVCM200000f921e388RCRD&vgnextchannel=137742b32a131610VgnVCM1000001d4a900aRCRD',
    notas: 'Temáticamente muy cercana a lo nuestro, pero exige censo municipal y dos tercios de la actividad en Madrid capital.',
    confianza: 'media',
  },
  {
    nombre: 'Jóvenes y Cercanas (Fundación Montemadrid y CaixaBank)',
    organismo: 'Fundación Montemadrid, con CaixaBank',
    ambito: 'Madrid',
    publico: ['asociaciones'],
    tematica: 'Apoyo a entidades sociales jóvenes: proyectos de acción social en Madrid o Castilla-La Mancha',
    cuantia: 'Hasta 30.000 € por proyecto, máximo 75% del coste',
    plazoInicio: '2025-06-06',
    plazoFin: '2025-06-27',
    estadoManual: null,
    estadoNota: 'IV edición cerrada y resuelta (350.000 € para 15 entidades); sin quinta edición anunciada a julio de 2026. La ventana suele ser en junio.',
    url: 'https://www.fundacionmontemadrid.es/convocatoria/jovenesycercanas/',
    notas: 'Dirigida justo a entidades como la nuestra: máximo 15 años de vida e ingresos por debajo de 500.000 €. El requisito es ejecutar el proyecto en la Comunidad de Madrid o Castilla-La Mancha.',
    confianza: 'alta',
  },
  {
    nombre: 'Tarifa Cero para autónomos (CAM)',
    organismo: 'Comunidad de Madrid · DG de Autónomos y Emprendimiento',
    ambito: 'Madrid',
    publico: ['pymes y autónomos', 'jóvenes'],
    tematica: 'Bonificación del 100% de la cuota de autónomos durante 12 meses, ampliable a 24 (menores de 30 entre los colectivos prioritarios)',
    cuantia: 'Cuota reducida + MEI bonificadas al 100% · presupuesto 7 M€ en 2026',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'abierta',
    estadoNota: 'Plazo permanente: se solicita en los 3 meses posteriores a cada periodo bonificado de 12 meses.',
    url: 'https://sede.comunidad.madrid/ayudas-becas-subvenciones/ayudas-tarifa-cero',
    notas: 'Para difundir entre jóvenes emprendedores madrileños; requiere domicilio de actividad en la Comunidad de Madrid.',
    confianza: 'alta',
  },

  // ── La Rioja (fase 2) ────────────────────────────────────
  {
    nombre: 'Subvenciones IRJ a asociaciones juveniles',
    organismo: 'Instituto Riojano de la Juventud (Gobierno de La Rioja)',
    ambito: 'La Rioja',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Programas juveniles: talleres, campamentos, voluntariado, intercambios y educación no formal (12-30 años)',
    cuantia: 'Paquete de juventud 2026: 1,6 M€ globales',
    plazoInicio: null,
    plazoFin: '2026-04-30',
    estadoManual: null,
    estadoNota: 'Convocatoria 2026 cerrada el 30/04. Anual: se publica en marzo con plazo hasta final de abril.',
    url: 'https://web.larioja.org/',
    notas: 'Exige inscripción en el registro riojano de asociaciones juveniles y destinatarios residentes: solo viable con delegación o socios riojanos. Trámite electrónico 01807.',
    confianza: 'media',
  },
  {
    nombre: 'Iniciativas emblemáticas de juventud (IRJ)',
    organismo: 'Instituto Riojano de la Juventud (Gobierno de La Rioja)',
    ambito: 'La Rioja',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Autonomía y emancipación juvenil: empleabilidad, participación y fortalecimiento asociativo',
    cuantia: '225.000 € (dotación 2026)',
    plazoInicio: null,
    plazoFin: '2026-04-30',
    estadoManual: null,
    estadoNota: 'Convocatoria 2026 cerrada el 30/04; línea reciente dentro del paquete anual de juventud (marzo).',
    url: 'https://web.larioja.org/',
    notas: 'Mismo requisito de arraigo riojano que la línea general del IRJ.',
    confianza: 'media',
  },
  {
    nombre: 'Infancia y juventud (Ayto. de Logroño)',
    organismo: 'Ayuntamiento de Logroño · Lojoven',
    ambito: 'La Rioja',
    publico: ['asociaciones', 'jóvenes'],
    tematica: 'Asociacionismo juvenil: actividades, ocio alternativo, formación y animación comunitaria',
    cuantia: '',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'anunciar',
    estadoNota: 'Convocatoria 2026 no localizada a 16/07. Pauta anual: extracto en el BOR a finales de marzo con 15 días hábiles.',
    url: 'https://lojoven.es/becas-y-subvenciones',
    notas: 'Exige registro de entidades ciudadanas de Logroño y actividad en la ciudad.',
    confianza: 'media',
  },
  {
    nombre: 'Proyectos Sociales La Rioja (Fundación la Caixa)',
    organismo: 'Fundación la Caixa, con la red de CaixaBank en La Rioja',
    ambito: 'La Rioja',
    publico: ['asociaciones'],
    tematica: 'Proyectos sociales para personas vulnerables: infancia, inclusión, inserción sociolaboral, salud mental',
    cuantia: 'En torno a 50.000 € por proyecto en las territoriales 2026 (sin confirmar para La Rioja)',
    plazoInicio: null,
    plazoFin: null,
    estadoManual: 'anunciar',
    estadoNota: 'Confirmadas 18 convocatorias territoriales 2026 (una por comunidad); fechas de La Rioja pendientes de confirmar en la web oficial.',
    url: 'https://fundacionlacaixa.org/es/convocatorias-sociales-descripcion',
    notas: 'Sustituye en la práctica a la antigua convocatoria de Fundación Caja Rioja-CaixaBank. Exige sede o actividad registrada en el territorio.',
    confianza: 'media',
  },
  {
    nombre: 'ADER · Promoción de emprendedores (PPA)',
    organismo: 'ADER · Agencia de Desarrollo Económico de La Rioja',
    ambito: 'La Rioja',
    publico: ['pymes y autónomos', 'jóvenes'],
    tematica: 'Subvención a fondo perdido para primeras inversiones de nuevas empresas y autónomos',
    cuantia: '35% de la inversión (entre 3.000 y 70.000 €), con extras en municipios pequeños',
    plazoInicio: null,
    plazoFin: '2026-12-11',
    estadoManual: null,
    estadoNota: 'Abierta hasta el 11/12/2026 a las 14:00; pauta anual.',
    url: 'https://www.ader.es/ayudas/ayudas-por-areas/emprendedores/ppa-promocion-de-emprendedores-programa-de-adquisicion-de-primeros-activos/',
    notas: 'Para difundir entre jóvenes que emprendan en La Rioja: exige domicilio fiscal y centro de trabajo allí y empresa de nueva creación.',
    confianza: 'alta',
  },
];
